Cora:
  seed: 1998
  learning_rate: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  num_epochs: 300
  weight_decay: 0.00001
  eps: 0.5
  alpha: 0.1
  beta: 0.01
  lamb: 0
CiteSeer:
  seed: 4
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.0
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  tau: 0.9
  num_epochs: 300
  weight_decay: 0.00001
  eps: 2
  alpha: 0.01
  beta: 0.001
  lamb: 1
Amazon-Computers:
   seed: 3
   learning_rate: 0.01
   num_hidden: 128
   num_proj_hidden: 128
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.6
   drop_edge_rate_2: 0.3
   drop_feature_rate_1: 0.2
   drop_feature_rate_2: 0.3
   tau: 0.2
   num_epochs: 2000
   weight_decay: 0.00001
   eps: 0.5
   alpha: 0.001
   beta: 0.01
   lamb: 0
Amazon-Photo:
   seed: 4
   learning_rate: 0.1
   num_hidden: 256
   num_proj_hidden: 64
   activation: "relu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.3
   drop_edge_rate_2: 0.5
   drop_feature_rate_1: 0.1
   drop_feature_rate_2: 0.1
   tau: 0.3
   num_epochs: 2000
   weight_decay: 0.00001
   eps: 2
   alpha: 0.1
   beta: 0.01
   lamb: 1
Coauthor-CS:
   seed: 1
   learning_rate: 0.0005
   num_hidden: 256
   num_proj_hidden: 256
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.3
   drop_edge_rate_2: 0.2
   drop_feature_rate_1: 0.3
   drop_feature_rate_2: 0.4
   tau: 0.4
   num_epochs: 1000
   weight_decay: 0.00001
   eps: 1.5
   alpha: 0.1
   beta: 0.001
   lamb: 0
Coauthor-Physics:
   seed: 1
   learning_rate: 0.01
   num_hidden: 128
   num_proj_hidden: 64
   activation: "rrelu"
   base_model: 'GCNConv'
   num_layers: 2
   drop_edge_rate_1: 0.4
   drop_edge_rate_2: 0.1
   drop_feature_rate_1: 0.1
   drop_feature_rate_2: 0.4
   tau: 0.5
   num_epochs: 1500
   weight_decay: 0.00001
   eps: 1
   alpha: 0.1
   beta: 0.001
   lamb: 0.5
